[project]
authors = ["Dan Allan <>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "event-driven-tiled-fetching"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
tiled-client = ">=0.1.0b14, <0.2"
ipython = ">=8.31.0,<9"
event-model = ">=1.22.3,<2"

[pypi-dependencies]
bluesky-tiled-plugins = ">=2.0.0b55, <3"
